### ISSUE TITLE
group-project command does not work

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/lagoon-cli#135]
**Describe the bug**
When running the `group-project` command, the result is
```
Error: graphql: Unauthorized
```

**To Reproduce**
1. `lagoon list group-projects --name foobar`
2. Result is `Error: graphql: Unauthorized`

**Expected behavior**
See a list of projects associated to group `foobar`

**Comment by steveworley** [comment]
It looks like this might be caused by blanket handling of error cases, a direct query to graphql shows that part of the response has an error and we assume that if errors are set the whole request is bad.

The error checking might need to test for `data: null` as well as error not being nil.

https://github.com/amazeeio/lagoon-cli/blob/master/pkg/lagoon/users/groups.go#L231

GraphQL can raise multiple errors during a query and the error key stores all of them

> The errors field, where all the errors accumulated during the execution of the operation are kept

If I send the query manually I get some results and an error and it looks like

```
{
  "errors": [
    {
      "message": "Unauthorized",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "allGroups",
        0,
        "projects",
        50
      ]
    }
  ],
  "data": {
    "allGroups": [
      {
        "projects": [ /* project list */ ]
      }
    ]
  }
}
```

**Comment by shreddedbacon** [comment]
So there is a bit more to this.
The query is fine, but the problem is in the lagoon API. Will raise an issue there to get the underlying problem resolved.

But will leave this open to address better error handling.

**Comment by shreddedbacon** [comment]
Underlying group unauthorised issue is related to https://github.com/amazeeio/lagoon/issues/1562

**Comment by tobybellwood** [comment]
not a CLI bug - handling in https://github.com/uselagoon/lagoon/issues/1562
