### ISSUE TITLE
deploytarget name on lagoon-get-environment

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon-cli#152]
**Is your feature request related to a problem? Please describe.**
It would be helpful to see the openshift/deploytarget a project is running on on the lagoon-get-project command

**Describe the solution you'd like**

```
ID  	PROJECTNAME	GITURL                                    	BRANCHES               	PULLREQUESTS	PRODUCTIONROUTE     	DEVENVIRONMENTS	DEVENVLIMIT	PRODUCTIONENV	AUTOIDLE    DeployTarget
1271	example   	git@github.com:example/example.git	^(dev|prod|release/.*)$	true        	https://example.net	5/5            	5          	prod         	1   us1-lagoon
```
Basically it would be the information from

```
    openshift {
      name
    }
```

**Comment by shreddedbacon** [comment]
Is this section of the query available to all users? Adding this *could* be a permission issue if say `developer` role doesn't have permission to query this field.

**Comment by seanhamlin** [comment]
Keen for this as well, as I find Lagoon CLI quite nice in scripting, having to do GraphQL in cURL to emulate this, was certainly not ideal.

**Comment by bomoko** [comment]
Discussing this in tech debt, perhaps the right level to surface this detail at is on the environment level, given that there are potentially many deploy target configs - the info may be somewhat misleading/a little useless depending on the setup.

**Comment by seanhamlin** [comment]
This bit me again recently. The information is vastly different in the `list` command compared to the `get` command. Ideally (IMO) the list command simply lists all environments you have access to, but the information contained in each environment is no different from `get`.

**Current workaround:**

In order to get the current deployTarget, I need to query the `list` command, and then enumerate through each returned environment to see if the namespace matches. Not super ideal.
