### ISSUE TITLE
lagoon logs command

### ISSUE THREAD

**Issue by smlx** [uselagoon/lagoon-cli#232]
**Is your feature request related to a problem? Please describe.**
Sometimes it might be easier to request logs from a Lagoon environment via the command line. This is simpler in cases where you know exactly which project/env you want to see logs for.

**Describe the solution you'd like**
It would be great if I could run a command like this and have logs printed to my terminal:
```
lagoon logs --project=... --environment=... --log-type=[application,router,container]
```

**Describe alternatives you've considered**
The logging web UI is fine, but sometimes a CLI is better and probably faster.

**Additional context**
This feature request would have to know about the logging solution of your specific installation of Lagoon, and probably be tied to Opensearch. I'm not sure if it would be better for the CLI to go through a Lagoon API endpoint for logs, or if it makes more sense to query Opensearch directly.

I'm also not sure if this idea even makes sense; this issue is just a discussion starter.

**Comment by shreddedbacon** [comment]
If we were to do something like this, due to how the API works/processes things, I think it would be best to try and query the Opensearch directly.

I do like the idea of being able to query logs, and I know Lagoon team has had discussions in the past about streaming/dumping logs from the pods themselves in a similar way to how SSH currently works, so this may be an alternative option too. I know it may not cover the same use-case as being able to query for historical logs like against Opensearch though.
