### ISSUE TITLE
Bug in lagoon list deploytargets

### ISSUE THREAD

**Issue by tnelson-doghouse** [uselagoon/lagoon-cli#276]
**Describe the bug**
I get an error message.  I shouldn't.  

**To Reproduce**
1. Run `lagoon list deploytargets --project wanderland-district-2021 --environment deploy/lagoon/production`

**Expected behavior**
Non-error output

**Actual behaviour**
`Error: graphql: Unauthorized: You don't have permission to "viewAll" on "openshift": {}`

**Desktop (please complete the following information):**
 - OS: in a Linux container (Fedora)
 - Browser: None
 - Version: lagoon v0.18.0 (go-1.16) -- built 2023-04-05T02:51:45Z

**Comment by shreddedbacon** [comment]
This is actually a valid error because you're using the command wrong. The `deploytargets` you're trying to reference here are actually the top level item also referenced as `kubernetes` or `openshift` in the API. But the CLI is calling them `deploytargets` because this is what we are transitioning towards.

General users don't have permission to view these as per lagoon RBAC matrix.

**Comment by tnelson-doghouse** [comment]
OK, thanks!
