### ISSUE TITLE
lagoon deploy results improvement

### ISSUE THREAD

**Issue by jordotech** [uselagoon/lagoon-cli#30]
**Is your feature request related to a problem? Please describe.**
running the lagoon deploy command says success immediately without knowing the results of the deployment

**Describe the solution you'd like**
I would like to watch the deployment logs (the same that are viewable in lagoon UI) live as they are happening.  Maybe a `--watch` flag?

**Additional context**
I ran a deployment with the cli and it said success.  The deployment failed however.

**Comment by shreddedbacon** [comment]
Currently, there is no way to stream the log output live from lagoon :(

At the moment, the best that can be done is to start a deployment, then poll the api for the status of the deployment until it completes. Once complete, it could dump the build log in one hit.

**Comment by jordotech** [comment]
That'll work, as long as you don't have to leave the terminal to see what actually happened

**Comment by shreddedbacon** [comment]
https://github.com/uselagoon/lagoon-cli/pull/294 changes the `lagoon get deployment` command to accept the build name. This hasn't been released yet, but it will be soon.

This will return the build after it has been triggered, you could after triggering the build wrap it in a loop that checks the output of the `get deployment` for the status then
```
BUILDNAME=$(lagoon deploy latest --project $project --environment $environment --force --returnData)
lagoon get deployment --project $project --environment $environment --name $BUILDNAME
```

`get deployment` also has the `--logs` flag to return the logs, but doing this repeatedly is kind of pointless because they only update when there are periodic status changes.

I'm going to close this issue out, as the release that contains this is being bundled at the moment.
